version: "3.9"
services:
  web:
    container_name: "todo_container"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /Todo
    ports:
      - "8000:8000"
    volumes:
      - .:/Todo
    depends_on:
      - db
  db:
    container_name: "todo_db"
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: "todo_db"
      MYSQL_ROOT_PASSWORD: "password" # 実運用ではより強固なパスワードを設定してください
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
